services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cloud-cleaner-backend
    ports:
      - "8084:8084"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-ap-south-1}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - PORT=8084
      - HOST=0.0.0.0
      - DEBUG=${DEBUG:-false}
    env_file:
      - ./backend/.env
    networks:
      - cloud-cleaner-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8084/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cloud-cleaner-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8084/api
      - NODE_ENV=production
    env_file:
      - ./frontend/.env
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - cloud-cleaner-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  cloud-cleaner-network:
    driver: bridge