"""add alert tracking to cost limit

Revision ID: 528d746b9d3a
Revises: 905d162768ad
Create Date: 2026-01-19 23:30:26.579219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '528d746b9d3a'
down_revision: Union[str, Sequence[str], None] = '905d162768ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_limits', sa.Column('last_alert_sent_at', sa.DateTime(), nullable=True))
    op.add_column('cost_limits', sa.Column('current_alert_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cost_limits', 'current_alert_level')
    op.drop_column('cost_limits', 'last_alert_sent_at')
    # ### end Alembic commands ###
